config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: :show

  def index
    @products = Product.search_for_index(params)
  end

  def show; end

  private

  def set_product
    @product = Product.find_by(id: params[:id])
    return redirect_to root_path, alert: "Product not found" if @product.blank?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_time(time)
    time = Time.parse(time) if time.kind_of? String
    time.strftime('%-d %b %Y at %-I:%M.%S %p')
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def render_tags(tags)
    tags.collect do |tag|
      content_tag(:span, tag, class: "label label-info m-l-xs")
    end.join.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Spockets Assignment</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Spockets Assignment", root_path, class: "navbar-brand" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/products/_details_model_body.html.erb
<div class="modal-dialog">

  <div class="modal-content">
    <div class="modal-body">
      <div class="panel panel-primary">
        <div class="panel-heading"><%= @product.title %></div>
        <div class="panel-body">
          <p><%= @product.description %></p>
          <div><strong>Price</strong> <%= @product.price %></div>
          <div><strong>Country</strong> <%= @product.country %></div>
          <div>
            <strong>Tags: </strong><%= render_tags(@product.tags) %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/products/_filter.html.erb
<%= form_tag(products_path, method: 'get', class: 'form-horizental') do %>
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 m-b-md">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <div class="row">
          <%= text_field_tag :keyword, params[:keyword], placeholder: 'Seach..', class: "form-control" %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
            <%= text_field_tag :price, params[:price], placeholder: 'Price', class: "form-control" %>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <%= select_tag(:price_operator, options_from_collection_for_select(Product::PRICE_OPERATORS, :second, :first,params[:price_operator]), class: 'form-control') %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-2 col-lg-2">
        <%= select_tag(:country, options_from_collection_for_select(Product::COUNTRIES, :to_s, :to_s, params[:country]), {class: 'form-control', prompt: 'Select Country'}) %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-2 col-lg-2">
        <%= select_tag(:order, options_from_collection_for_select(Product::SORTING.values, :to_s, :to_s, params[:order]), {class: 'form-control'}) %>
      </div>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<div class="clearfix"></div>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Product</h1>
</div>

  <div class="well">
    <%= render 'filter' %>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Country</th>
          <th>Price</th>
          <th>Tags</th>
          <th>Description</th>
          <th>Created At</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.title %></td>
            <td><%= product.country %></td>
            <td><%= product.price %></td>
            <td><%= render_tags(product.tags) %></td>
            <td><%= product.description %></td>
            <td><%= render_time product.created_at %></td>
            <td>
              <%= link_to product_path(product.id), remote: true do %>
                <span class="glyphicon glyphicon-eye-open"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<%= paginate @products %>
<div id="product_details" class="modal fade" role="dialog"></div>

app/views/products/show.js.erb
$("#product_details").html("<%= j render('details_model_body') %>");
$("#product_details").modal('show');

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  <% end %>
<% end %>